//////////////////////////
//// IGNORE THIS FILE ////
//////////////////////////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//// IGNORE THIS FILE ////
//////////////////////////
#region //// IGNORE THIS FILE ////
//// IGNORE THIS NAMESPACE ////
namespace PolarisGame
{
    //// IGNORE THIS CLASS ////
    class Program
    {
        //// IGNORE THIS METHOD ////
        static void Main(string[] args)
        {
            //// INITIALIZE IN GAME CLASS, NOT HERE!!! ////
            new Game().Run(); //// REQUIRED TO ALLOW FOR *GAME* INIT
        }
    }
}
#endregion
//////////////////////////